# Generated by Django 4.2.1 on 2023-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nkustnews',
            name='date',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nkustnews',
            name='url',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
